# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.13-slim-bookworm

# Copy local code to the container image.
ENV APP_HOME=/server
WORKDIR $APP_HOME
COPY requirements-server.txt ./

# Install server python requirements
RUN pip3 install --no-cache-dir -r requirements-server.txt
COPY . ./

ENTRYPOINT ["python3", "-m", "backup.server"]
